name: C++ CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt update && sudo apt install -y g++

      - name: Compile
        run: g++ "class Barang.cpp" -o program

      - name: Run Test
        run: ./program
